version: '3.9'

services:
    app:
        container_name: arv-controll
        restart: always
        build: .
        command: npm run start
        ports:
            - '5000'
        volumes:
            - .:/usr/app/arv
    nginx:
        container_name: nginx-server
        restart: always
        build: ./nginx
        ports:
            - "8080:80"