version: '3.7'

services:
    app:
        container_name: arv-controll
        restart: always
        build: .
        command: sh -c "npm run build && npm run start"
        ports:
            - '5000:5000'
        volumes:
            - .dist:/usr/app/arv
    # nginx:
    #     container_name: nginx-server
    #     restart: always
    #     build: ./nginx
    #     ports:
    #         - "80:80"
    #         - "443:443"