version: '3.7'

services:
    api-arv-controll:
        container_name: api-arv-controll
        restart: always
        build: .
        command: sh -c "npm run start:dev"
        ports:
            - '5000'
        volumes:
            - .:/usr/app/arv
    nginx:
        container_name: nginx-server
        restart: always
        build: ./nginx
        ports:
            - "8000:80"
        depends_on:
            - api-arv-controll
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf