version: '3.7'

services:
  api-arv-controll:
    container_name: api-arv-controll
    restart: always
    build: .
    command: sh -c "./scripts/start-app.sh"
    expose:
      - '5000'
    volumes:
      - .:/usr/app/arv
    environment:
      - NODE_ENV=production
  nginx:
    container_name: nginx-server
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
        - api-arv-controll
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./letsencrypt:/etc/letsencrypt