version: '3.7'

services:
  api-arv-controll:
    container_name: api-arv-controll
    restart: always
    build: .
    command: sh -c "./scripts/start-app.sh"
    expose:
      - '5000'
    volumes:
      - .:/usr/app/arv
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health-check"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
  nginx:
    container_name: nginx-server
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
        - api-arv-controll
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /root/letsencrypt:/etc/letsencrypt
      - ./build:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
